### PR TITLE
Added new widget in navigation bar

### PR DESCRIPTION
**Pull request by rahul13199kumar**
# Description 

Added new Widget in Navigation Bar with new features like , (UI)
(1)user can select year ,
(2) play quizzes , 
(3)search topics easily.

# changes

Updated Navigation Bar with (UI) .

# Screenshots

6fa5884b-3df9-45cf-b4f3-a8ead9b3f65e

### CODE REVIEW

**Comment by Rajwrita** [comment]
Thanks!

**Comment by ayush-670** [comment]
Hi Rahul! We closed the previous two PRs of yours because we thought that the changes would change the theme/branding of the App( in the case of the App icon), and secondly, the Home page UI changes were a bit blunt. 
We do like your improvisation of the Drawer and were about to merge this particular PR, but on merging it will also implement the above two changes, which we don't want. Hence, we are closing this PR and would like to request you to improvise only the Drawer to the repository with the latest commit ONLY.

The next time, go for one PR per change in the main branch, as multiple PRs would make the code a bit messy.
Wait for that PR to be merged/closed, and then you may proceed.

cc: Screenshots of the app, once we executed it on our system
SS1
SS2






Thanks and best regards.

**Comment by rahul13199kumar** [comment]
ya sure  , @ayush-670 . I improve the drawer , and do PR . 

Thanks :)

**Comment by rahul13199kumar** [comment]
# Hi @ayush-670  , Now problem has been resolved . Please Check #13 .

# Screenshots of the app, once executed  on real device

# Drawer ss
6fa5884b-3df9-45cf-b4f3-a8ead9b3f65e

# Splash Screen
 
Screenshot_1608141759

# Home page
Screenshot_1608141614


# Thankyou :)

**Pull request closed without merging**
